name: Build Executables

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed sovcal_gui.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: sovcal_gui_linux
          path: dist/sovcal_gui

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed sovcal_gui.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: sovcal_gui_macos
          path: dist/sovcal_gui

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed sovcal_gui.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: sovcal_gui_windows
          path: dist/sovcal_gui.exe

