name: Build Executables

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            extension: ''
            shell: bash
            artifact_name: sovcal_gui_linux
          - os: macos-latest
            extension: ''
            shell: bash
            artifact_name: sovcal_gui_macos
          - os: windows-latest
            extension: '.exe'
            shell: powershell
            artifact_name: sovcal_gui_windows
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5
      shell: ${{ matrix.shell }}

    - name: Build Executable
      run: |
        pyinstaller --onefile --windowed sovcal_gui.py
      shell: ${{ matrix.shell }}

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/sovcal_gui${{ matrix.extension }}

